sonar.projectKey=myapp
sonar.projectName=MyApp
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/bin/**, **/dist/**
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.host.url=http://192.168.179.119:9102/
sonar.login=sqp_f0542867efb79e21fec882b444135d8347ff841d